// Generated by CoffeeScript 1.7.1
(function() {
  var Model, add_timestamp, db, get_timestamp, schema, types,
    __slice = [].slice,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  db = require("../db");

  schema = db.schema;

  types = schema.types;

  get_timestamp = function() {
    var now;
    now = new Date();
    return new Date(now.getTime() + (now.getTimezoneOffset()));
  };

  add_timestamp = function(obj) {
    var ts;
    ts = get_timestamp();
    obj.created_at = ts;
    obj.updated_at = ts;
    return obj;
  };

  Model = (function() {
    Model.table = "";

    Model.timestamp = false;

    Model.primary_key = "id";

    function Model() {
      this._primary_key = this.constructor.primary_keys();
      this._table = this.constructor.table;
      this._timestamp = this.constructor.timestamp;
    }

    Model.validate = function(values) {
      var key, result, value;
      if (!this.constraints) {
        return true;
      }
      for (key in values) {
        value = values[key];
        if (!this.constraints[key]) {
          continue;
        }
        result = this.constraints[key](value);
        if (result != null) {
          console.log(result);
        }
        if (result !== true) {
          return result;
        }
      }
      return true;
    };

    Model.primary_keys = function() {
      if ("string" === typeof this.primary_key) {
        return [this.primary_key];
      } else {
        return this.primary_key;
      }
    };

    Model.load_all = function(rows) {
      var i, row, _results;
      _results = [];
      for (i in rows) {
        row = rows[i];
        _results.push(this.load(row));
      }
      return _results;
    };

    Model.load = function(row) {
      var k, obj, v;
      obj = new this();
      for (k in row) {
        v = row[k];
        obj[k] = v;
      }
      return obj;
    };

    Model.encode_key = function() {
      var args, i;
      args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      args = args[0];
      return ((function() {
        var _i, _ref, _results;
        _results = [];
        for (i = _i = 0, _ref = args.length - 1; 0 <= _ref ? _i <= _ref : _i >= _ref; i = 0 <= _ref ? ++_i : --_i) {
          _results.push("" + (db.escape_name(this.primary_keys()[i])) + " = " + (db.escape_var(args[i])));
        }
        return _results;
      }).call(this)).join(" and ");
    };

    Model.find = function() {
      var args, k, r, v, where;
      args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      where = "";
      if (Array.isArray(args && "object" !== typeof args[0])) {
        where = this.encode_key(args);
      } else {
        where = ((function() {
          var _ref, _results;
          _ref = args[0];
          _results = [];
          for (k in _ref) {
            v = _ref[k];
            _results.push("" + (db.escape_name(k)) + " = " + (db.escape_var(v)));
          }
          return _results;
        })()).join(" and ");
      }
      r = db.select("* FROM " + (db.escape_name(this.table)) + " WHERE " + where + " LIMIT 1");
      return r.then((function(_this) {
        return function(result) {
          if (result.rowCount > 0) {
            return _this.load(result.rows[0]);
          }
        };
      })(this));
    };

    Model.find_all = function(keys, by_key) {
      var r, v;
      if (by_key == null) {
        by_key = this.primary_key;
      }
      keys = (function() {
        var _i, _len, _results;
        _results = [];
        for (_i = 0, _len = keys.length; _i < _len; _i++) {
          v = keys[_i];
          _results.push(db.escape_var(v));
        }
        return _results;
      })();
      r = db.select("* FROM " + (db.escape_name(this.table)) + " WHERE " + by_key + " in (" + (keys.join(", ")) + ")");
      return r.then((function(_this) {
        return function(result) {
          if (result.rowCount > 0) {
            return _this.load_all(result.rows);
          }
        };
      })(this));
    };

    Model.select = function(conditions, fields) {
      var condition, k, q, r, v;
      q = ["* FROM " + (db.escape_name(this.table))];
      if (conditions) {
        condition = ((function() {
          var _results;
          _results = [];
          for (k in conditions) {
            v = conditions[k];
            _results.push("" + (db.escape_name(k)) + " = " + (db.escape_var(v)));
          }
          return _results;
        })()).join(" and ");
        q.push(" WHERE " + condition);
      }
      r = db.select(q.join(""));
      return r.then((function(_this) {
        return function(result) {
          if (result.rowCount > 0) {
            return _this.load_all(result.rows);
          }
        };
      })(this));
    };

    Model.create = function(info) {
      var r;
      if (this.timestamp) {
        info = add_timestamp(info);
      }
      r = db.insert(this.table, info, this.primary_keys());
      return r.then((function(_this) {
        return function(result) {
          return _this.load(_this.find(result.rows[0]));
        };
      })(this));
    };

    Model.prototype["delete"] = function() {
      var conditions, k, _i, _len, _ref;
      conditions = {};
      _ref = this._primary_key;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        k = _ref[_i];
        conditions[k] = this[k];
      }
      return db["delete"](this._table, conditions);
    };

    Model.prototype.update = function() {
      var args, conditions, first, k, values, _i, _j, _len, _len1, _ref;
      first = arguments[0], args = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
      conditions = {};
      values = {};
      _ref = this._primary_key;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        k = _ref[_i];
        conditions[k] = this[k];
      }
      if ("string" === typeof first) {
        args.push(first);
        for (_j = 0, _len1 = args.length; _j < _len1; _j++) {
          k = args[_j];
          values[k] = this[k];
        }
      } else {
        values = first;
      }
      if (this._timestamp) {
        values.updated_at = get_timestamp();
      }
      return db.update(this._table, values, conditions);
    };

    Model.has_many = function(model) {
      var model_id, model_name, new_model, new_tbl, primary_key, this_id, this_name;
      model_name = model.name.toLowerCase();
      model_id = "" + model_name + "_id";
      this_name = this.name.toLowerCase();
      this_id = "" + this_name + "_id";
      new_tbl = "" + this_name + "_" + model_name;
      primary_key = [this_id, model_id];
      schema.create_table(new_tbl, [
        {
          name: "" + this_name + "_id",
          type: types.foreign_key
        }, {
          name: "" + model_name + "_id",
          type: types.foreign_key
        }, "PRIMARY KEY (" + (primary_key.join(", ")) + ")"
      ]);
      new_model = db.models[new_tbl] = (function(_super) {
        __extends(_Class, _super);

        function _Class() {
          return _Class.__super__.constructor.apply(this, arguments);
        }

        _Class.table = new_tbl;

        _Class.primary_key = primary_key;

        return _Class;

      })(Model);
      this.prototype["has_" + model_name] = function(info) {
        return model.find(info).then((function(_this) {
          return function(m) {
            var t;
            if (!m) {
              return;
            }
            t = {};
            t[model_id] = m.id;
            t[this_id] = _this.id;
            return new_model.find(t);
          };
        })(this));
      };
      this.prototype["add_" + model_name] = function(m) {
        return this["has_" + model_name](m).done((function(_this) {
          return function(r) {
            if (r) {
              return;
            }
            return model.find(m).then(function(m) {
              var t;
              if (!m) {
                return;
              }
              t = {};
              t[model_id] = m.id;
              t[this_id] = _this.id;
              return new_model.create(t);
            });
          };
        })(this));
      };
      return this.prototype["remove_" + model_name] = function(m) {
        return this["has_" + model_name](m).done((function(_this) {
          return function(r) {
            if (!r) {
              return;
            }
            return model.find(m).then(function(m) {
              var t;
              t = {};
              t[model_id] = m.id;
              t[this_id] = _this.id;
              return new_model.find(t).then(function(other) {
                return other["delete"]();
              });
            });
          };
        })(this));
      };
    };

    return Model;

  })();

  module.exports = Model;

}).call(this);
